baseurl: /self # no custom domain
repository: metreeca/self # local testing (https://help.github.com/articles/repository-metadata-on-github-pages/)
remote_theme: metreeca/docs

exclude: [Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      project: "self"
      version: "0.49.0"
      tagline: "Metreeca Self-Service SPARQL Tool"
      release: "https://github.com/metreeca/self/releases/tag/v0.49.0"
