baseurl: /self # no custom domain
repository: metreeca/self # local testing (https://help.github.com/articles/repository-metadata-on-github-pages/)
remote_theme: metreeca/docs

exclude: [Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      project: "${project.artifactId}"
      version: "${project.version}"
      tagline: "${project.name}"
      release: "${project.scm.url}/releases/tag/v${project.version}"
